-- =============================================
-- STRATEGY & BUSINESS CONFIG TABLES
-- =============================================

-- Business configuration (brand, avatar, offer, positioning)
CREATE TABLE IF NOT EXISTS business_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  section TEXT NOT NULL UNIQUE,
  data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Weekly strategy snapshots (for tracking evolution)
CREATE TABLE IF NOT EXISTS strategy_weekly (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start DATE NOT NULL UNIQUE,
  posts_count INTEGER DEFAULT 0,
  videos_count INTEGER DEFAULT 0,
  tofu_count INTEGER DEFAULT 0,
  mofu_count INTEGER DEFAULT 0,
  bofu_count INTEGER DEFAULT 0,
  avg_engagement NUMERIC(8,4) DEFAULT 0,
  total_reach INTEGER DEFAULT 0,
  total_saves INTEGER DEFAULT 0,
  total_shares INTEGER DEFAULT 0,
  followers_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Strategy benchmarks (key metrics to track)
CREATE TABLE IF NOT EXISTS strategy_benchmarks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  value NUMERIC(10,2) NOT NULL DEFAULT 0,
  unit TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Content strategy plan (generated by AI)
CREATE TABLE IF NOT EXISTS strategy_plan (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  planned_date DATE NOT NULL,
  funnel_stage TEXT CHECK (funnel_stage IN ('tofu', 'mofu', 'bofu')),
  content_type TEXT DEFAULT 'reel',
  topic TEXT,
  hook_angle TEXT,
  cta_type TEXT CHECK (cta_type IN ('none', 'soft', 'medium', 'hard')),
  reference_profile TEXT,
  notes TEXT,
  status TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'draft', 'approved', 'posted', 'skipped')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_strategy_plan_date ON strategy_plan(planned_date);
CREATE INDEX IF NOT EXISTS idx_strategy_plan_status ON strategy_plan(status);
CREATE INDEX IF NOT EXISTS idx_strategy_weekly_week ON strategy_weekly(week_start);

-- Trigger for business_config updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS business_config_updated_at ON business_config;
CREATE TRIGGER business_config_updated_at
  BEFORE UPDATE ON business_config
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- ADD MISSING COLUMNS TO EXISTING TABLES
-- =============================================

-- Missing columns in posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reach_count INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS ig_media_id TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS impressions_count INTEGER DEFAULT 0;

-- Missing column in batches table
ALTER TABLE batches ADD COLUMN IF NOT EXISTS strategic_note TEXT;
